# fly.toml app configuration file generated for nyumatcdn on 2024-01-22T13:12:53-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nyumatcdn"
primary_region = "sea"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
